# Generated by Django 5.0.6 on 2024-06-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='content',
            field=models.TextField(default='test1'),
            preserve_default=False,
        ),
    ]
